build.gradle

https://tools.hmcts.net/jira/browse/FACT-359
This stems from a recent CVE that is high enough risk to block building the API any further. I've identified a spring version (2.3.9.RELEASE) which is still compatible with the current codebase, which will bring the spring.framework.security dependency up to 5.3.8.RELEASE. This should mitigate the issue exploit whilst still ensuring compatibility across the board with our codebase.
```
[ ] Yes
[X] No
```

FACT-359 - Upgraded from Spring Boot 2.3.6.RELEASE to 2.3.9.RELEASE

---

src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/ServiceAreaRepositoryTest.java
src/main/resources/db/migration/V073__remove_servicearea_ocmc_ccbc.sql

https://tools.hmcts.net/jira/browse/FACT-357
Reverted due to causing an issue with the logic of how the money-claims journey occurs. Explanation for this can be [found here](https://tools.hmcts.net/jira/browse/FACT-373?focusedCommentId=977583&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-977583). Solution implemented in front-end instead ([relevant PR](https://github.com/hmcts/fact-frontend/pull/278))
```
[ ] Yes
[X] No
```

FACT-357 - Reverted changes introduced in previous fix

---

src/integrationTest/java/uk/gov/hmcts/dts/fact/ApplicationTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/CourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/mapit/MapItService.java
src/main/java/uk/gov/hmcts/dts/fact/mapit/MapitClient.java
src/main/java/uk/gov/hmcts/dts/fact/mapit/MapitHealthIndicator.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/dts/fact/mapit/MapitHealthIndicatorTest.java

https://tools.hmcts.net/jira/browse/FACT-375
Add the ability to check whether the Mapit service is up and running when calling the FaCT API health endpoint. If the Mapit service is down, the overall health status will be down.
```
[ ] Yes
[x] No
```

FACT-375 - Add custom health check for mapit and incorporate that into existing healthcheck

---

src/main/java/uk/gov/hmcts/dts/fact/controllers/SearchController.java
src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/SearchControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-376
https://tools.hmcts.net/jira/browse/FACT-378
Implemented ability to search by postcode area of law and local authority.
Only used when deprecated API is used for 'Children' area of law requests.
```
[ ] Yes
[X] No
```

FACT-378 - Fixed issues with local authority not being taken into account on deprecated search endpoint

---

src/main/java/uk/gov/hmcts/dts/fact/controllers/SearchController.java
src/main/java/uk/gov/hmcts/dts/fact/exception/InvalidPostcodeException.java
src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-364
Added new exception and subsequent handler to determine that MapIt has been supplied with an invalid postcode.
Updated test to expect InvalidPostcodeException rather than an empty array.
```
[ ] Yes
[X] No
```

FACT-364 - Updated deprecated endpoint to make use of new exception for invalid postcodes

---

build.gradle

https://tools.hmcts.net/jira/browse/FACT-448
Patch for CVE-2021-29425, specified apache commons-io to a version which has this issue patched.
```
[ ] Yes
[X] No
```

FACT-448 - Patch for CVE-2021-29425

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtGeneralInfoEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtOpeningTimeEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/util/TestUtil.java
src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/OpeningTypeRepositoryTest.java
src/integrationTest/resources/deprecated/aylesbury-magistrates-court-and-family-court.json
src/main/java/uk/gov/hmcts/dts/fact/config/security/SecurityConfiguration.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtGeneralInfoController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtOpeningTimesController.java
src/main/java/uk/gov/hmcts/dts/fact/entity/OpeningTime.java
src/main/java/uk/gov/hmcts/dts/fact/model/CourtForDownload.java
src/main/java/uk/gov/hmcts/dts/fact/model/OpeningTime.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/OpeningTime.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtOpeningTimeService.java
src/main/resources/db/migration/V090__add_extra_court_opening_types.sql
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtGeneralInfoControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtOpeningTimesControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtOpeningTimeServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-408
- Fix issue where exception is thrown when adding new opening times to courts with no existing opening times
- Update standard court endpoints so that opening type in the admin table is used instead of the opening type in the opening time table.
- Prefix admin court opening types and general info endpoints with “/admin” path
```
[ ] Yes
[x] No
```

FACT-408 - Fix issue with adding new opening times to courts with no existing opening times

---

src/main/java/uk/gov/hmcts/dts/fact/model/deprecated/OldCourt.java

Updated deprecated court object to present cci code value in both county_location_code and cci_code property.
```
[ ] Yes
[x] No
```

C100-patch - Added in cci_code field to deprecated court object.

---

build.gradle

Update SpringBoot framework to 2.3.10.RELEASE to bump up SpringSecurity dependency to safe 2.3.9 build
```
[ ] Yes
[x] No
```

CVE-2021-22112-Patch - Updated SpringBoot to 2.3.10.RELEASE

---

src/main/java/uk/gov/hmcts/dts/fact/exception/GlobalControllerExceptionHandler.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtTypesService.java
src/main/java/uk/gov/hmcts/dts/fact/util/CourtType.java
src/main/java/uk/gov/hmcts/dts/fact/util/MapCourtCode.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtTypesControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtTypeServiceTest.java
src/test/java/uk/gov/hmcts/dts/fact/util/MapCourtCodeTest.java

https://tools.hmcts.net/jira/browse/FACT-70
Minor update for comparing court types from admin portal. Store court types in enum for comparison with inout from admin portal and throw error if not found.
```
[ ] Yes
[x] No
```

FACT-70 - Minor update for comparing court types from admin portal

---

build.gradle

Upgraded to SpringBoot 2.3.11.RELEASE due to CVE-2021-22118 - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22118
```
[ ] Yes
[X] No
```

CVE-2021-22118-Patch - Upgraded SpringBoot to 2.3.11.RELEASE

---

src/main/java/uk/gov/hmcts/dts/fact/services/admin/list/AdminLocalAuthorityService.java

https://tools.hmcts.net/jira/browse/FACT-188
Fix bug in local authority duplication check to use correct integer equality.
```
[ ] Yes
[x] No
```

FACT-188 Fix bug in local authority duplication check to use correct integer equality.

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtLocalAuthoritiesEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtLocalAuthoritiesController.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtLocalAuthoritiesService.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtLocalAuthoritiesControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtLocalAuthoritiesServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-783
Remove redundant GET local authorities endpoint from edit court API. This now resides in the 'list' API.
```
[ ] Yes
[x] No
```

FACT-783 Remove redundant GET local authorities endpoint from edit court API.

---

src/main/resources/db/migration/V118__add_money_claims_to_courts.sql

https://tools.hmcts.net/jira/browse/FACT-842
https://tools.hmcts.net/jira/browse/FACT-843
Add money claims area of law to Taunton County Court and Isle of Wight Combined Court
```
[ ] Yes
[x] No
```

FACT-842 - Add money claims area of law to Taunton County Court and Isle of Wight Combined Court

---

src/main/java/uk/gov/hmcts/dts/fact/entity/AreaOfLaw.java
src/main/java/uk/gov/hmcts/dts/fact/entity/Court.java
src/main/java/uk/gov/hmcts/dts/fact/model/AreaOfLaw.java
src/main/java/uk/gov/hmcts/dts/fact/model/Court.java
src/main/resources/db/migration/V122__make_additional_link_per_court.sql
src/main/resources/db/migration/V123__move_additional_links_to_area_of_law_table.sql
src/test/java/uk/gov/hmcts/dts/fact/entity/CourtTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/AreaOfLawTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtTest.java

https://tools.hmcts.net/jira/browse/FACT-881
- Move Financial Remedy and Business and Property into area of law table
- Make use of the alt-name and alt_name fields on the area of law table for in-person court display name
```
[ ] Yes
[x] No
```

FACT-881 - Move Financial Remedy and Business and Property into area of law table

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtFacilityEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/Facility.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/FacilityType.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtFacilityService.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtFacilityServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-885
Sort facilities based on the sort order of the type before returning through the admin endpoints
```
[ ] Yes
[x] No
```

FACT-885 - Sort facilities based on the sort order of the type before returning through the admin endpoints

---

charts/fact-api/Chart.yaml

After work on DTSPO-6881, pods failed to restart in 01 cluster for taking too long. New java-chart release has been published to accommodate for this - https://github.com/hmcts/chart-java/releases/tag/3.7.1. @damongreen123
```
[ ] Yes
[x] No
```

Update chart to new release

---

build.gradle
config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtAddressEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtPostcodeEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/exception/GlobalControllerExceptionHandler.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtAdditionalLinkControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtAddressControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtApplicationUpdateControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtAreasOfLawControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtContactControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtEmailsControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtFacilityControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtGeneralInfoControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtLocalAuthoritiesControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtOpeningTimeControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtPostcodeControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtSpoeAreasOfLawControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtTypesAndCodesControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsControllerTest.java

https://tools.hmcts.net/jira/browse/FACT-1178
changed exceptions to return json object instead of returning a string. former error messages now return under 'message' name value pair.
```
[ ] Yes
[ x ] No
```

FACT-1178 changed exceptions to return json instead of string

---

src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtRepository.java

https://tools.hmcts.net/jira/browse/FACT-1244
added a search query split and use the first word (assuming it's location) to grab matching town courts and fuzzy matches for following search results
```
[ ] Yes
[ x ] No
```

FACT-1244 changed sql to use first word as first search criteria

---

src/main/java/uk/gov/hmcts/dts/fact/entity/Court.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtLocalAuthorityAreaOfLawRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminService.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-1784
- Adds the cascading removal of the address of court so court can be deleted
- Adds deleting the local authority area of law of court before the court is deleted
- Updates unit tests for court deletion method
```
[ ] Yes
[x] No
```

FACT-1784 - fixes court deletion

---

src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminAuditService.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminAuditControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminAuditServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-2000
changed audit page to show date in the timestamp as gmt/bst
```
[ ] Yes
[x] No
```

FACT-2000 altered audit page to show in gmt/bst on creationdate
