hmcts/fact-api

build.gradle
src/integrationTest/java/uk/gov/hmcts/dts/fact/config/SwaggerPublisherTest.java
src/integrationTest/java/uk/gov/hmcts/dts/fact/controllers/GetWelcomeTest.java
src/main/java/uk/gov/hmcts/dts/fact/Application.java
src/main/java/uk/gov/hmcts/dts/fact/config/SwaggerConfiguration.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/RootController.java
src/test/java/uk/gov/hmcts/dts/fact/DemoUnitTest.java

Refactor package name to be dts rather than reform

Move from Reform to DTS

---

charts/fact-api/Chart.yaml
charts/fact-api/values.preview.template.yaml
charts/fact-api/values.yaml
infrastructure/main.tf

https://tools.hmcts.net/jira/browse/CTF-42
Add db and vault infrastructure

Add infrastructure for database

---

config/pmd/ruleset.xml
src/integrationTest/java/uk/gov/hmcts/dts/fact/controllers/deprecated/CourtsControllerTest.java
src/integrationTest/java/uk/gov/hmcts/dts/fact/controllers/deprecated/SearchControllerTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/deprecated/CourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/deprecated/SearchController.java

https://tools.hmcts.net/jira/browse/CTF-46
Add api endpoiiunt stubs
```
[ ] Yes
[X] No
```

CTF-46: Add api endpoint stubs

---

build.gradle
charts/fact-api/Chart.yaml
charts/fact-api/values.preview.template.yaml
charts/fact-api/values.yaml
src/integrationTest/java/uk/gov/hmcts/dts/fact/config/FlywayConfigurationTest.java
src/main/java/uk/gov/hmcts/dts/fact/config/FlywayConfiguration.java
src/main/java/uk/gov/hmcts/dts/fact/data/migration/FlywayNoOpStrategy.java
src/main/java/uk/gov/hmcts/dts/fact/exception/PendingMigrationScriptException.java
src/main/resources/application.yaml
src/main/resources/db/migration/.gitkeep
src/test/java/uk/gov/hmcts/dts/fact/data/migration/FlywayNoOpStrategyTest.java

https://tools.hmcts.net/jira/browse/CTF-43
Add flyway
```
[ ] Yes
[X] No
```

CTF-43: Add flyway

---

docker-compose.yml
docker/database/Dockerfile

https://tools.hmcts.net/jira/browse/CTF-44
Add database to docker
```
[ ] Yes
[o] No
```

Ctf 44 add docker database

---

build.gradle
src/test/java/uk/gov/hmcts/dts/fact/data/migration/FlywayNoOpStrategyTest.java

https://tools.hmcts.net/jira/browse/CTF-43
Update test to junit5
```
[ ] Yes
[X] No
```

Update test to junit5

---

Jenkinsfile_CNP
build.gradle
src/functionalTest/java/uk/gov/hmcts/dts/fact/CourtsEndpointTest.java

https://tools.hmcts.net/jira/browse/CTF-58
Add functional test
```
[ ] Yes
[x] No
```

CTF-58: Add functional test

---

Jenkinsfile_CNP

CTF-58: Archive test reports

---

config/checkstyle/checkstyle.xml
config/pmd/ruleset.xml
src/main/java/uk/gov/hmcts/dts/fact/model/CourtEmail.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtEmailTest.java

Add some more coverage

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/CourtsEndpointTest.java
src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/CourtRepositoryTest.java
src/integrationTest/resources/courts.json
src/main/java/uk/gov/hmcts/dts/fact/controllers/CourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/entity/Court.java
src/main/java/uk/gov/hmcts/dts/fact/model/Court.java
src/main/java/uk/gov/hmcts/dts/fact/model/CourtReference.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/CourtsControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java

Ctf 41 search

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/CourtsEndpointTest.java
src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/CourtRepositoryTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/CourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/CourtsControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java

Ctf 41 clean up

---

charts/fact-api/Chart.yaml
charts/fact-api/values.preview.template.yaml

Ctf 50 add postgres extensions

---

build.gradle
charts/fact-api/Chart.yaml
charts/fact-api/values.yaml
src/integrationTest/java/uk/gov/hmcts/dts/fact/config/FeignConfigurationTest.java
src/integrationTest/resources/application.properties
src/main/java/uk/gov/hmcts/dts/fact/Application.java
src/main/java/uk/gov/hmcts/dts/fact/config/FeignConfiguration.java
src/main/java/uk/gov/hmcts/dts/fact/model/Court.java
src/main/java/uk/gov/hmcts/dts/fact/services/MapitClient.java
src/main/java/uk/gov/hmcts/dts/fact/services/model/Coordinates.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/dts/fact/controllers/CourtsControllerTest.java

https://tools.hmcts.net/jira/browse/CTF-50
Add mapit integration
```
[ ] Yes
[x] No
```

CTF-50: Add mapit integration

---

docker-compose.yml

Use correct docker image
```
[ ] Yes
[ ] No
```

Fix docker image

---

docker-compose.yml

N/A
Add dummy variable for mapit key
```
[ ] Yes
[√ ] No
```

Add dummy variable for mapit key

---

src/main/java/uk/gov/hmcts/dts/fact/model/Court.java
src/main/java/uk/gov/hmcts/dts/fact/util/Utils.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtTest.java
src/test/java/uk/gov/hmcts/dts/fact/util/UtilsTest.java

Strip urlencoded areaoflaw

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/SearchEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtRepository.java

https://tools.hmcts.net/jira/browse/FACT-119
Support welsh search criteria
```
[ ] Yes
[√] No
```

FACT-119: Support Welsh search criteria

---

build.gradle
charts/fact-api/Chart.yaml
charts/fact-api/values.yaml
config/owasp/suppressions.xml
docker-compose.yml
src/functionalTest/java/uk/gov/hmcts/dts/fact/AuthException.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/CourtsEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/OAuthClient.java
src/main/java/uk/gov/hmcts/dts/fact/config/SecurityConfiguration.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/CourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java

Added endpoint with oauth resource server authentication

Added oauth api auth

---

src/integrationTest/java/uk/gov/hmcts/dts/fact/services/MapitClientTest.java
src/main/java/uk/gov/hmcts/dts/fact/Application.java
src/main/java/uk/gov/hmcts/dts/fact/mapit/Coordinates.java
src/main/java/uk/gov/hmcts/dts/fact/mapit/MapitClient.java
src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java

N/A
Add test for mapit and tidy up
```
[ ] Yes
[x] No
```

mapit test

---

src/integrationTest/java/uk/gov/hmcts/dts/fact/ApplicationTest.java
src/integrationTest/java/uk/gov/hmcts/dts/fact/config/SwaggerPublisherTest.java
src/main/resources/application.yaml
src/main/resources/bootstrap.yaml

https://tools.hmcts.net/jira/browse/FACT-120
Add appinsights

Add appinsights

---

src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/CourtRepositoryTest.java
src/integrationTest/resources/courts.json
src/main/java/uk/gov/hmcts/dts/fact/controllers/CourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/entity/Court.java
src/main/java/uk/gov/hmcts/dts/fact/model/CourtReference.java
src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/CourtsControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java

Fact 65 view all courts

---

src/main/java/uk/gov/hmcts/dts/fact/model/CourtReference.java
src/test/java/uk/gov/hmcts/dts/fact/config/LocaleResolverTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtReferenceTest.java
src/test/java/uk/gov/hmcts/dts/fact/util/UtilsTest.java

Improve quality gate

---

src/main/java/uk/gov/hmcts/dts/fact/entity/Service.java
src/main/java/uk/gov/hmcts/dts/fact/entity/ServiceArea.java
src/main/java/uk/gov/hmcts/dts/fact/model/Service.java
src/main/java/uk/gov/hmcts/dts/fact/model/ServiceArea.java
src/main/resources/db/migration/V008__add_welsh_to_servicea_and_servicearea.sql
src/test/java/uk/gov/hmcts/dts/fact/model/ServiceAreaTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/ServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-143
Add welsh to services endpoint
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[√] No

FACT-143: Add welsh to services endpoint

---

src/main/resources/db/migration/V009__add_access_scheme.sql

https://tools.hmcts.net/jira/browse/FACT-102
Add boolean for access_scheme to inperson courts
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[X] No

Access scheme

---

src/main/java/uk/gov/hmcts/dts/fact/entity/InPerson.java
src/main/java/uk/gov/hmcts/dts/fact/model/Court.java
src/main/java/uk/gov/hmcts/dts/fact/model/deprecated/CourtWithDistance.java
src/main/java/uk/gov/hmcts/dts/fact/model/deprecated/OldCourt.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtTest.java

https://tools.hmcts.net/jira/browse/FACT-102
Add boolean for access_scheme to inperson courts
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[X] No

Access scheme 2

---

src/main/java/uk/gov/hmcts/dts/fact/services/AdminService.java

N/A
Fix sonar error
```
[ ] Yes
[x] No
```

Fix sonar error

---

src/integrationTest/java/uk/gov/hmcts/dts/fact/mapit/MapitClientTest.java
src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/ServiceRepositoryTest.java
src/integrationTest/resources/service.json
src/integrationTest/resources/services.json
src/main/java/uk/gov/hmcts/dts/fact/controllers/ServicesController.java
src/main/java/uk/gov/hmcts/dts/fact/entity/Service.java
src/main/java/uk/gov/hmcts/dts/fact/model/Service.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/ServiceRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/ServiceService.java
src/main/resources/db/migration/V010__add_service_slug.sql
src/test/java/uk/gov/hmcts/dts/fact/config/security/RoleAspectTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/ServicesControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/ServiceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/ServiceServiceTest.java
src/test/resources/service-areas.json

https://tools.hmcts.net/jira/browse/FACT-168
Add service slug
Does this PR introduce a breaking change? (check one with "x")
[X] Yes - get service by name removed
[ ] No

FACT-168:Add service slug

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/AdminCourtsEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/CourtsEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/OAuthClient.java
src/main/java/uk/gov/hmcts/dts/fact/config/security/Role.java
src/main/java/uk/gov/hmcts/dts/fact/config/security/RoleAspect.java
src/main/java/uk/gov/hmcts/dts/fact/config/security/SecurityConfiguration.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/services/AdminService.java
src/test/java/uk/gov/hmcts/dts/fact/config/security/RoleAspectTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/AdminServiceTest.java

FACT 94 include super admin in role check

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/AdminCourtsEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/OAuthClient.java
src/main/java/uk/gov/hmcts/dts/fact/config/security/RoleAspect.java
src/main/java/uk/gov/hmcts/dts/fact/config/security/SpringRolesProvider.java
src/test/java/uk/gov/hmcts/dts/fact/config/security/RoleAspectTest.java
src/test/java/uk/gov/hmcts/dts/fact/config/security/SpringRolesProviderTest.java

N/A
Add auth tests
```
[ ] Yes
[x] No
```

Add auth tests

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/CourtsEndpointTest.java

remove duplicate test

---

src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtRepository.java

Update the search to ignore postal addresses

remove postal addresses from search

---

src/main/resources/db/migration/V011__service_add_welsh.sql
src/main/resources/db/migration/V012__servicearea_add_welsh.sql.sql

https://tools.hmcts.net/jira/browse/FACT-183
FACT-183: Welsh translations
FACT-190: Update probate description
```
[ ] Yes
[X] No
```

FACT-183: Welsh translations

---

src/integrationTest/resources/service.json
src/main/java/uk/gov/hmcts/dts/fact/entity/ServiceArea.java
src/main/java/uk/gov/hmcts/dts/fact/model/ServiceArea.java
src/test/java/uk/gov/hmcts/dts/fact/model/ServiceAreaTest.java

Add missing fields

---

src/main/java/uk/gov/hmcts/dts/fact/config/appinsights/DependencyProfiler.java
src/main/java/uk/gov/hmcts/dts/fact/config/appinsights/DependencyProfilerAspect.java
src/main/java/uk/gov/hmcts/dts/fact/mapit/MapitClient.java
src/test/java/uk/gov/hmcts/dts/fact/config/appinsights/DependencyProfilerAspectTest.java

https://tools.hmcts.net/jira/browse/FACT-191
Add logging for mapit API calls

Add logging for mapit calls

---

src/main/resources/db/migration/V017__add_missing_courts.sql

N/A
Add missing courts
```
[ ] Yes
[ x] No
```

add missing courts

---

src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/ServiceAreaRepositoryTest.java
src/integrationTest/resources/service.json
src/main/resources/db/migration/V018__add_national_courts_to_service_areas.sql

Add service area to national service centres
```
[ ] Yes
[x] No
```

Link service areas to national service centres

---

src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/ServiceAreaRepositoryTest.java
src/integrationTest/resources/service.json
src/main/java/uk/gov/hmcts/dts/fact/entity/ServiceArea.java
src/main/java/uk/gov/hmcts/dts/fact/model/ServiceArea.java
src/main/resources/db/migration/V020__add_servicearea_areaoflaw_link.sql
src/test/java/uk/gov/hmcts/dts/fact/model/ServiceAreaTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/AdminServiceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/ServiceAreaServiceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/ServiceServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-197
Link service area to area of law.  Return area of law name in service area json.
```
[ ] Yes
[x] No
```

Link service areas to areas of law

---

src/main/resources/db/migration/V021__add_court_details.sql

https://tools.hmcts.net/jira/browse/FACT-139
Add missing contact details
```
[ ] Yes
[ ] No
```

add missing court contact details

---

src/main/resources/db/migration/V023__add_civil_partnership_to_court_mapping.sql

FACT-140
Add civilr partnership
```
[ ] Yes
[x] No
```

add civil partnership

---

src/main/java/uk/gov/hmcts/dts/fact/entity/ServiceArea.java
src/main/java/uk/gov/hmcts/dts/fact/model/ServiceArea.java
src/main/resources/db/migration/V024__add_service_text.sql
src/test/java/uk/gov/hmcts/dts/fact/model/ServiceAreaTest.java

Add serviceareas text

---

src/main/java/uk/gov/hmcts/dts/fact/model/ServiceArea.java

Add text for ServiceArea

---

src/main/resources/db/migration/V027__edit_service_text.sql

Added the second sentence to the service text in the database as this is dynamic too.
```
[ ] Yes
[ X ] No
```

Update text to include the rest of the dynamic sentence

---

src/integrationTest/resources/service.json
src/main/resources/db/migration/V028__add_onlineurl_for_civil_partnership_.sql

Add online url

---

src/test/java/uk/gov/hmcts/dts/fact/model/CourtAddressTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/ServiceAreaTest.java

Increase test coverage

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/AdminCourtsEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/CourtGeneral.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtGeneralTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/AdminServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-210
Add slug to admin general json so that the view link works on fact-admin edit page.
```
[ ] Yes
[x] No
```

Add slug to general admin json

---

src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/ServiceAreaRepositoryTest.java
src/integrationTest/resources/service-area.json
src/integrationTest/resources/service.json
src/main/resources/db/migration/V029__add_courts_to_servicearea.sql

Add more courts to service area table
```
[ ] Yes
[ ] No
```

Add courts to servicearea

---

src/main/java/uk/gov/hmcts/dts/fact/entity/CourtWithDistance.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtRepository.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtWithDistanceRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java

Change finding nearest to sql

---

charts/fact-api/Chart.yaml
charts/fact-api/values.yaml

Update base java chart for autoscaling

---

src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/CourtWithDistanceRepositoryTest.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtPostcode.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtWithDistance.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtWithDistanceRepository.java

https://tools.hmcts.net/jira/browse/FACT-138
```
[ ] Yes
[X] No
```

fact 138 - include query for civil path

---

src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/CourtWithDistanceRepositoryTest.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtWithDistanceRepository.java

Add local authority query
Add local authority query
```
[ ] Yes
[ ] No
```

Add local authority query

---

src/main/java/uk/gov/hmcts/dts/fact/entity/ServiceArea.java
src/main/resources/db/migration/V030__add_catchment_method_to_servicearea.sql

Add catchment type

---

src/main/java/uk/gov/hmcts/dts/fact/config/security/RoleAspect.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/CourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/SearchController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/ServiceAreasController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/ServicesController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/services/AdminService.java
src/main/java/uk/gov/hmcts/dts/fact/services/MapitService.java
src/main/java/uk/gov/hmcts/dts/fact/services/ServiceAreaService.java
src/main/java/uk/gov/hmcts/dts/fact/services/ServiceService.java

N/A
Make autowired components constructor params
```
[ ] Yes
[x] No
```

make autowired beans constructor params

---

src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/CourtWithDistanceRepositoryTest.java
src/main/java/uk/gov/hmcts/dts/fact/model/CourtReferenceWithDistance.java
src/main/java/uk/gov/hmcts/dts/fact/model/ServiceAreaType.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtWithDistanceRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
src/main/java/uk/gov/hmcts/dts/fact/services/search/NearestCourtsByCourtPostcodeAndAreaOfLawSearch.java
src/main/java/uk/gov/hmcts/dts/fact/services/search/NearestCourtsByPostcodeAndAreaOfLawSearch.java
src/main/java/uk/gov/hmcts/dts/fact/services/search/NearestRegionalByAreaOfLawAndLocalAuthoritySearch.java
src/main/java/uk/gov/hmcts/dts/fact/services/search/NearestTenByAreaOfLawAndLocalAuthoritySearch.java
src/main/java/uk/gov/hmcts/dts/fact/services/search/PostcodeSearchForServiceAreaFactory.java
src/main/java/uk/gov/hmcts/dts/fact/services/search/Search.java
src/main/resources/db/migration/V032__add_regional_court_to_local_authority_link.sql
src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/search/NearestCourtsByCourtPostcodeAndAreaOfLawSearchTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/search/NearestCourtsByPostcodeAndAreaOfLawSearchTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/search/NearestRegionalByAreaOfLawAndLocalAuthoritySearchTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/search/NearestTenByAreaOfLawAndLocalAuthoritySearchTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/search/PostcodeSearchForServiceAreaFactoryTest.java

https://tools.hmcts.net/jira/browse/FACT-135
Add regional local authority prximity search
```
[ ] Yes
[x] No
```

Add regional local authority proxmity search

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/SearchEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/model/CourtReferenceWithDistance.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtWithDistanceRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/search/NearestRegionalByAreaOfLawAndLocalAuthoritySearch.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtReferenceWithDistanceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/search/NearestRegionalByAreaOfLawAndLocalAuthoritySearchTest.java

https://tools.hmcts.net/jira/browse/FACT-135
Fix postcode search for regional and local authority search
```
[ ] Yes
[x] No
```

Fix regional local authority search

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/SearchEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/SearchController.java
src/main/java/uk/gov/hmcts/dts/fact/model/ServiceAreaWithCourtReferencesWithDistance.java
src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
src/test/java/uk/gov/hmcts/dts/fact/model/ServiceAreaWithCourtReferencesWithDistanceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java

Add ServiceAreaWithCourtReferencesWithDistance

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/SearchEndpointTest.java

Fix functional search test
```
[ ] Yes
[ ] No
```

Fix functional search test

---

src/main/java/uk/gov/hmcts/dts/fact/controllers/CourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/SearchController.java
src/main/java/uk/gov/hmcts/dts/fact/model/CourtReferenceWithDistance.java
src/main/java/uk/gov/hmcts/dts/fact/model/deprecated/CourtWithDistance.java
src/test/java/uk/gov/hmcts/dts/fact/config/security/RoleAspectTest.java
src/test/java/uk/gov/hmcts/dts/fact/mapit/MapitDataTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtAddressTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtGeneralTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/AdminServiceTest.java

Remove sonar issues
```
[ ] Yes
[x] No
```

Fix sonar issues

---

src/main/java/uk/gov/hmcts/dts/fact/controllers/CourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/SearchController.java

Fix deprecated sonar issue
```
[ ] Yes
[x] No
```

Fix deprecated sonar issues

---

charts/fact-api/Chart.yaml
charts/fact-api/values.yaml

set cpu mem levels

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/SearchEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/services/search/NearestCourtsByCourtPostcodeAndAreaOfLawSearch.java

civil-postcode-fix

---

src/main/java/uk/gov/hmcts/dts/fact/model/CourtReferenceWithDistance.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtReferenceWithDistanceTest.java

changing decimal place to 1

---

README.md
src/main/resources/db/migration/V037__fix_data.sql

https://tools.hmcts.net/jira/browse/FACT-224
Fix in person 
```
[ ] Yes
[ ] No
```

FACT_224: fix inperson table

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/AdminCourtsEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/CourtsEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/SearchEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/ServiceAreaEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/ServiceEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/model/Court.java
src/main/java/uk/gov/hmcts/dts/fact/util/CourtAddressTypeConverter.java
src/test/java/uk/gov/hmcts/dts/fact/config/LocaleResolverTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/CourtsControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/SearchControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/ServiceAreasControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/ServicesControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/util/CourtAddressTypeConverterTest.java

Add tests for uncovered logic
Minor tidying
```
[ ] Yes
[x] No
```

Add tests for uncovered logic

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/ServiceEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/entity/Service.java
src/main/resources/db/migration/V038__add_sort_order.sql

FACT_244: Add sort order to service areas

---

src/main/resources/db/migration/V039__set_displayed_flag_for_service_centres.sql

Set displayed true for new service centres

---

src/main/resources/db/migration/V046__update_service_area_data.sql

https://tools.hmcts.net/jira/browse/FACT-260
Fix service area data:
Add divorce and civil partnership regional centres
Set adoption catchment_method to local-authority
```
[ ] Yes
[x] No
```

Add regional centres and fix adoption catchment type

---

src/main/java/uk/gov/hmcts/dts/fact/model/Court.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtTest.java

https://tools.hmcts.net/jira/browse/FACT-245
```
[ ] Yes
[X] No
```

Fact 245 info with html

---

src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtWithDistanceRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/search/CivilSearch.java
src/test/java/uk/gov/hmcts/dts/fact/services/search/CivilSearchTest.java

https://tools.hmcts.net/jira/browse/FACT-257
Partial poscode search
```
[ ] Yes
[ ] No
```

FACT-257: partial postcode searches

---

src/main/java/uk/gov/hmcts/dts/fact/model/admin/CourtGeneral.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtGeneralTest.java

fact 94 - clean up

---

src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtWithDistanceRepository.java

FACT-257: partial postcode searches use exact match

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/AdminCourtsEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/CourtGeneral.java
src/main/java/uk/gov/hmcts/dts/fact/services/AdminService.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtGeneralTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/AdminServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-93
Admin Journey - closed courts and access scheme flags
```
[ ] Yes
[ ] No
```

FACT-93: closed courts and access scheme flags

---

build.gradle
config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/dts/fact/AdminCourtsEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/entity/Court.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtOpeningTime.java
src/main/java/uk/gov/hmcts/dts/fact/entity/OpeningTime.java
src/main/java/uk/gov/hmcts/dts/fact/model/Court.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/Court.java
src/main/java/uk/gov/hmcts/dts/fact/model/deprecated/OldCourt.java
src/main/java/uk/gov/hmcts/dts/fact/services/AdminService.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/admin/CourtTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/AdminServiceTest.java
src/test/resources/full-birmingham-civil-and-family-justice-centre-entity.json

https://tools.hmcts.net/jira/browse/FACT-73
Opening hours
```
[ ] Yes
[ ] No
```

Fact 73 opening times

---

src/main/resources/db/migration/V049__set_regional_service_centres_not-inperson.sql

https://tools.hmcts.net/jira/browse/FACT-274
Set regional service centres to not in person

FACT-274: Set regional service centres to Not In-Person

---

src/main/resources/db/migration/V050__new_areas_of_law.sql

https://tools.hmcts.net/jira/browse/FACT-256
Add new areas of law

FACT-256: Add new areas of law

---

src/main/resources/db/migration/V052__change_servicearea.sql

https://tools.hmcts.net/jira/browse/FACT-271
Change major crime button name and hint text

FACT-271: Change major crime button name and hint text

---

src/main/resources/db/migration/V054__change_servicearea.sql

https://tools.hmcts.net/jira/browse/FACT-282
Add missing apostrophe

FACT-282: Add missing apostrophe

---

src/main/resources/db/migration/V056__service_area_welsh.sql

https://tools.hmcts.net/jira/browse/FACT-297
Welsh

FACT-2967: Add welsh translation for new aol

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/ServiceEndpointTest.java
src/main/resources/db/migration/V058__update_crime.sql

https://tools.hmcts.net/jira/browse/FACT-283
https://tools.hmcts.net/jira/browse/FACT-290
update crime serivce area

FACT-283, FACT-290: Update crime service area

---

src/main/resources/db/migration/V059__close_Criminal_Offences_Service_Centre.sql

https://tools.hmcts.net/jira/browse/FACT-295
Close criminal offences service centre

FACT-295: close criminal offences service centre

---

src/main/resources/db/migration/V061__Add_CCBC_to_not_in_person_court.sql

https://tools.hmcts.net/jira/browse/FACT-328
Add CCBC to not-inperson courts

FACT-328: Add CCBC to not-inperson courts

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/dts/fact/model/CourtForDownload.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtForDownloadTest.java

https://tools.hmcts.net/jira/browse/FACT-166
Add additional fields

FACT-166: Add aditional fields for download

---

src/main/java/uk/gov/hmcts/dts/fact/model/CourtForDownload.java

https://tools.hmcts.net/jira/browse/FACT-166
Separate DX

FACT-166: separate DX

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/AdminCourtsEndpointTest.java

N/A
Add opening hours to test to prevent frontend test failing

Add opening hours to test to prevent frontent tests failing

---

Jenkinsfile_CNP

https://github.com/hmcts/fact-api/compare/master...FACT-288
Sync branches with master

FACT-288: sync branches with master

---

src/main/resources/db/migration/V011__service_add_welsh.sql
src/main/resources/db/migration/V014__add_servicearea_slug.sql

https://tools.hmcts.net/jira/browse/FACT-361
- Updated pre-existing flyway transformation files to use correct Welsh translations where previously incorrect translations were used.
```
[ ] Yes
[X] No
```

FACT-361 - Implemented changes for go-live requirements

---

src/main/resources/db/migration/V011__service_add_welsh.sql
src/main/resources/db/migration/V014__add_servicearea_slug.sql
src/main/resources/db/migration/V067__update_welsh_translations.sql

https://tools.hmcts.net/jira/browse/FACT-361
- Fixed an issue with a flyway transformation change that was done for this task previously.
- Added new/fixed translations into a new transformation file.
```
[ ] Yes
[X] No
```

FACT-361 - Reverted bad flyway transformation and added new translations to new transformation

---

src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/ServiceAreaRepositoryTest.java
src/main/resources/db/migration/V071__fix_court_service_areas.sql

https://tools.hmcts.net/jira/browse/FACT-357
Set service area for CCBC and online civil money claims (civil-money-claims-service-centre, county-court-business-centre-ccbc).
```
[ ] Yes
[x] No
```

FACT-357 - Fixed issues with missing service area on certain not-in-person courts.

---

src/main/resources/db/migration/V072__fix_incorrect_data.sql

https://tools.hmcts.net/jira/browse/FACT-368
Fixed details of courts that changed addresses/emails/contact details AFTER ctf portal was closed, meaning data changes were missing in prod data cut. 
```
[ ] Yes
[x] No
```

FACT-368 - Fixed incorrect/out-of-date data existing in prod data

---

config/pmd/ruleset.xml
src/main/java/uk/gov/hmcts/dts/fact/model/ServiceAreaType.java
src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
src/main/java/uk/gov/hmcts/dts/fact/util/Utils.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-365
https://tools.hmcts.net/jira/browse/FACT-380
https://tools.hmcts.net/jira/browse/FACT-381
https://tools.hmcts.net/jira/browse/FACT-382
Fixed issues with Scottish and Northern Irish postcode search results not filtered on the deprecated search endpoint.
```
[ ] Yes
[x] No
```

FACT-365 - Fixed issues with Scottish and Northern Irish postcode search results not filtered on the deprecated search endpoint

---

src/main/resources/db/migration/V074__update_bradford_magistrates_alert.sql

https://tools.hmcts.net/jira/browse/FACT-384
Simple flyway transformation to add alert message to court, targeted by court slug
```
[ ] Yes
[X] No
```

FACT-384 - Added flyway transformation to set alert message for bradford & keighley magistrates court

---

src/main/resources/db/migration/V075__update_welsh_translation_to_facility_and_service_type.sql

https://tools.hmcts.net/jira/browse/FACT-361
Update some welsh language translations in the database to correct casing and wording issues.
```
[ ] Yes
[x] No
```

FACT-361 - Corrected some welsh language translations in database

---

README.md

trigger build Update README.md

---

charts/fact-api/Chart.yaml
charts/fact-api/values.yaml

Autoscaling - bump chart

---

src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-386
Use fallback proximity search for mismatch between the local authority returned from the Mapit service and FaCT database.
```
[ ] Yes
[x] No
```

FACT-386 - Fixed Northampton postcode issue due to local authority mismatch between Mapit and FaCT database

---

src/main/resources/db/migration/V076__batch_court_changes_1.sql

https://tools.hmcts.net/jira/browse/FACT-383
Changed court details as requested in batch sheet of changes.
```
[ ] Yes
[X] No
```

FACT-383 - Flyway transformation for court data change request batch 1

---

src/main/resources/db/migration/V079__update_Poole_court_opening_hours.sql

https://tools.hmcts.net/jira/browse/FACT-398
Court content changes - Update Poole Magistrates' court opening hour.
```
[ ] Yes
[ ] No
```

FACT-398 - Update Poole Magistrates' court opening hour

---

src/main/resources/db/migration/V079__update_Poole_court_opening_hours.sql
src/main/resources/db/migration/V080__varioius_court_details_update.sql

https://tools.hmcts.net/jira/browse/FACT-393
https://tools.hmcts.net/jira/browse/FACT-397
Update building facilities content for Southampton, Weymouth and Bournemouth Combined courts
```
[ ] Yes
[x] No
```

FACT-393 - Update building facilities content for Southampton, Weymouth and Bournemouth Combined courts

---

charts/fact-api/Chart.yaml

Bump base java chart version Update Chart.yaml

---

src/main/resources/db/migration/V081__batch_court_changes_3.sql

FACT-400, FACT-403, FACT-406, FACT-413, FACT-414, FACT-418
https://tools.hmcts.net/jira/browse/FACT-400
https://tools.hmcts.net/jira/browse/FACT-403
https://tools.hmcts.net/jira/browse/FACT-406
https://tools.hmcts.net/jira/browse/FACT-413
https://tools.hmcts.net/jira/browse/FACT-414
https://tools.hmcts.net/jira/browse/FACT-418
Updated court details data with flyway transformation
```
[ ] Yes
[X] No
```

FaCT - Batch changes for court data

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCommon.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtOpeningTimeEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtsEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/CourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/SearchController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/ServiceAreasController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/ServicesController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtOpeningTimesController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminRole.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtOpeningTime.java
src/main/java/uk/gov/hmcts/dts/fact/exception/GlobalControllerExceptionHandler.java
src/main/java/uk/gov/hmcts/dts/fact/model/OpeningTime.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtOpeningTimeService.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminService.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtOpeningTimesControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtOpeningTimeServiceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminServiceTest.java
src/test/resources/opening-times.json

https://tools.hmcts.net/jira/browse/FACT-408
Add new admin endpoints for getting and updating court opening times
```
[ ] Yes
[x] No
```

FACT-408 - Add new admin endpoints for getting and updating court opening times

---

README.md
src/main/resources/db/migration/V082__batch_court_changes_4.sql

https://tools.hmcts.net/jira/browse/FACT-432
Flyway transformation for court data changes in batch 4
```
[ ] Yes
[X] No
```

FACT-432 - Court Batch Changes 4

---

src/main/resources/db/migration/V083__batch_court_changes_5.sql

https://tools.hmcts.net/jira/browse/FACT-436
Flyway data transformations for court data changes batch 5
```
[ ] Yes
[X] No
```

FACT-436 - Court data changes batch 5

---

README.md
src/main/resources/db/migration/V084__batch_court_changes_6.sql

https://tools.hmcts.net/jira/browse/FACT-451
Court data batch changes 6
```
[ ] Yes
[X] No
```

FACT-451 - Court data changes batch 6

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCommon.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtOpeningTimeEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtsEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/CourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/SearchController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/ServiceAreasController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/ServicesController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtOpeningTimesController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminRole.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtOpeningTime.java
src/main/java/uk/gov/hmcts/dts/fact/exception/GlobalControllerExceptionHandler.java
src/main/java/uk/gov/hmcts/dts/fact/model/OpeningTime.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtOpeningTimeService.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminService.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtOpeningTimesControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtOpeningTimeServiceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminServiceTest.java
src/test/resources/opening-times.json

https://tools.hmcts.net/jira/browse/FACT-408
Add new admin API endpoint for retrieving and updating opening times
```
[ ] Yes
[x] No
```

FACT-407 - Add new API endpoints for admin opening times

---

build.gradle
src/main/java/uk/gov/hmcts/dts/fact/controllers/SearchController.java
src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
src/main/java/uk/gov/hmcts/dts/fact/services/search/IProximitySearch.java
src/main/java/uk/gov/hmcts/dts/fact/services/search/ProximitySearch.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/dts/fact/controllers/SearchControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/search/ProximitySearchTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-366
New endpoint to search for the 10 nearest courts based on the postcode only. 
```
[ ] Yes
[ ] No
[x] Hopefully not
```

FACT-366 - Added new postcode search feature

---

src/integrationTest/java/uk/gov/hmcts/dts/fact/mapit/MapitClientTest.java
src/main/resources/db/migration/V085__batch_court_changes_7.sql

Disabled MapItClientTests till a solution can be found for issues with key not being requested from AAT key vault
```
[ ] Yes
[X] No
```

MapIt key-issue patch

---

src/main/resources/db/migration/V085__batch_court_changes_7.sql

https://tools.hmcts.net/jira/browse/FACT-457
Updated court data using flyway transformation
```
[ ] Yes
[X] No
```

FACT-457 - Court batch changes 7

---

src/main/resources/db/migration/V087__batch_court_changes_8.sql

https://tools.hmcts.net/jira/browse/FACT-458
Flyway data transformation for court batch changes 8
```
[ ] Yes
[X] No
```

FACT-458 - Court batch changes 8

---

src/main/resources/db/migration/V088__tameside_magistrates_court_alert_1.sql

https://tools.hmcts.net/jira/browse/FACT-474
Updated tameside alert message as urgent.
```
[ ] Yes
[X] No
```

FACT-474 - Tameside update 1

---

src/main/resources/db/migration/V089__tameside_magistrates_court_alert_2.sql

https://tools.hmcts.net/jira/browse/FACT-478
Removed tameside alert
```
[ ] Yes
[X] No
```

FACT-478 - Tameside update 2

---

Jenkinsfile_CNP
README.md
build.gradle
src/functionalTest/java/uk/gov/hmcts/dts/fact/util/OAuthClient.java

https://tools.hmcts.net/jira/browse/FACT-479
Remove default authentication provider URL, admin usernames and password for functional tests
```
[ ] Yes
[x] No
```

FACT-479 - Remove default authentication provider URL, admin usernames and password for functional tests

---

src/test/java/uk/gov/hmcts/dts/fact/util/MapCourtCodeTest.java

https://tools.hmcts.net/jira/browse/FACT-445
Added MapCourtCodeTests 
```
[ ] Yes
[ x] No
```

FACT-445 - MapCourtCodeTests added 

---

src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtTypesService.java

FACT-445 :- ) 
```
[ ] Yes
[ ] No
```

addressing sonarcube issue

---

src/main/resources/db/migration/V091__breathing_space_emails.sql

https://tools.hmcts.net/jira/browse/FACT-411
https://tools.hmcts.net/jira/browse/FACT-417
- Added in Breathing Space emails for launch of Breathing Space in May.
```
[ ] Yes
[X] No
```

FACT-411 - Added batch of Breathing Space emails into DB

---

src/main/resources/db/migration/V092__batch_changes_9.sql

https://tools.hmcts.net/jira/browse/FACT-492
Court batch changes 9
```
[ ] Yes
[x] No
```

FACT-492 - Batch court changes 9

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtGeneralInfoEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/CourtGeneralInfo.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtGeneralInfoControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtGeneralInfoServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-493
Return in person court information from admin general info endpoint.
```
[ ] Yes
[x] No
```

FACT-493 - Return in person court information from admin general info endpoint

---

src/main/resources/db/migration/V094__batch_court_changes_11.sql

https://tools.hmcts.net/jira/browse/FACT-505
Batch changes of court data through flyway transformation
```
[ ] Yes
[x] No
```

FACT-505 - Batch court changes 11

---

README.md
src/main/resources/db/migration/V097__reassign_criminal_email_and_contact_types.sql

https://tools.hmcts.net/jira/browse/FACT-74
https://tools.hmcts.net/jira/browse/FACT-95
Reassign 'Criminal' e-mail and contact types to 'Crown court' or 'Magistrates court'
```
[ ] Yes
[x] No
```

FACT-74 - Reassign 'Criminal' e-mail and contact types to 'Crown court' or 'Magistrates court'

---

src/main/resources/db/migration/V098__batch_court_changes_12.sql

https://tools.hmcts.net/jira/browse/FACT-513
Court batch changes 12 using flyway transformation
```
[ ] Yes
[X] No
```

FACT-513 - Court batch changes 12

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/CourtsEndpointTest.java
src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/CourtRepositoryTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/CourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/CourtsControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-525
```
[ ] Yes
[ x] No
```

Fact 525 - New endpoint for searching by prefix and active boolean

---

README.md

Update readme file to kick off Jenkins build again
```
[ ] Yes
[x] No
```

FACT-529 - Update readme file to kick off Jenkins build again

---

src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/CourtRepositoryTest.java
src/main/java/uk/gov/hmcts/dts/fact/entity/Court.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtContact.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtEmail.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtOpeningTime.java

https://tools.hmcts.net/jira/browse/FACT-528
Update timestamp column on the search_court table when court content is updated
```
[ ] Yes
[x] No
```

FACT-528 - Update timestamp column on the search_court table when court content is updated

---

src/main/resources/db/migration/V103__batch_court_changes_13.sql

https://tools.hmcts.net/jira/browse/FACT-536
Court batch changes 13
```
[ ] Yes
[x] No
```

FACT-536 - Court batch changes 13

---

src/main/resources/db/migration/V104__W_Yorkshire_Enforcement_Office.sql

https://tools.hmcts.net/jira/browse/FACT-542
Removed duplicate number from West Yorkshire Enforcement Office
```
[ ] Yes
[x] No
```

FACT-542 - Fixed duplicate number on West Yorkshire Enforcement Office

---

src/main/resources/db/migration/V105__newcastle_crown_magistrates_court_update.sql

https://tools.hmcts.net/jira/browse/FACT-549
Small content update (typo in the facility section) for Newcastle upon Tyne Crown Court and Magistrates Court
```
[ ] Yes
[x] No
```

FACT-549 - Small content update for Newcastle upon Tyne Crown Court and Magistrates Court

---

src/main/resources/db/migration/V106__batch_court_changes_14.sql

https://tools.hmcts.net/jira/browse/FACT-586
Court batch changes 14
```
[ ] Yes
[x] No
```

FACT-586 - Court Batch Changes 14

---

src/main/resources/db/migration/V107__batch_court_changes_15.sql

https://tools.hmcts.net/jira/browse/FACT-587
Court batch changes 15
```
[ ] Yes
[x] No
```

FACT-587 - Court batch changes 15

---

src/main/resources/db/migration/V108__batch_court_changes_16.sql

https://tools.hmcts.net/jira/browse/FACT-631
Court batch changes 16
```
[ ] Yes
[x] No
```

FACT-631 - Court Batch Changes 16

---

src/main/resources/db/migration/V109__batch_court_changes_17.sql

https://tools.hmcts.net/jira/browse/FACT-668
Court batch changes 17
```
[ ] Yes
[x] No
```

FACT-668 - Court Batch Changes 17

---

src/main/resources/db/migration/V110__batch_court_changes_18.sql

https://tools.hmcts.net/jira/browse/FACT-687
Court batch changes 18
```
[ ] Yes
[x] No
```

FACT-687 - Court Batch Changes 18

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtPostcodeEndpointTest.java
src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/CourtPostcodeRepositoryTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtPostcodeController.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtPostcodeRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtPostcodeService.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtPostcodeControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtPostcodeServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-703
Add new endpoint to move postcodes to a different court
```
[ ] Yes
[x] No
```

FACT-703 - Add new endpoint to move postcodes to a different court

---

src/main/java/uk/gov/hmcts/dts/fact/model/CourtReference.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtReferenceTest.java

https://tools.hmcts.net/jira/browse/FACT-680
```
[ ] Yes
[x ] No
```

returning displayed value with court reference object

---

src/main/resources/db/migration/V115__add_write_to_us_address_for_Ipswich_Court.sql

https://tools.hmcts.net/jira/browse/FACT-749
Add new 'Write to us' address for Ipswich County Court
```
[ ] Yes
[x] No
```

FACT-749 - Content changes : Add new 'Write to us' address for Ipswich County Court

---

charts/fact-api/values.preview.template.yaml
src/functionalTest/java/uk/gov/hmcts/dts/fact/CourtsEndpointTest.java
src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/CourtRepositoryTest.java
src/integrationTest/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/CourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
src/main/java/uk/gov/hmcts/dts/fact/services/validation/PostcodeValidator.java
src/main/resources/db/migration/V116__enable_fuzzy_matching_search.sql
src/test/java/uk/gov/hmcts/dts/fact/controllers/CourtsControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/validation/PostcodeValidatorTest.java

https://tools.hmcts.net/jira/browse/FACT-388
Enable fuzzy matching for searching by court name, address and town name
```
[ ] Yes
[x] No
```

FACT-388 - Enable fuzzy matching for court search

---

src/main/resources/db/migration/V117__remove_money_claims_from_middlesbrough_court.sql

Remove money claims area of law from Middlesbrough County Court
```
[ ] Yes
[x] No
```

FACT-602 - Remove money claims area of law from Middlesbrough County Court

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtFacilityEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/list/AdminFacilitiesEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtFacilityController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/list/AdminFacilitiesController.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtFacility.java
src/main/java/uk/gov/hmcts/dts/fact/entity/Facility.java
src/main/java/uk/gov/hmcts/dts/fact/entity/FacilityType.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/Facility.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/FacilityType.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtFacilityRepository.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/FacilityTypeRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtFacilityService.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/list/AdminFacilityService.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtFacilityControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/list/AdminFacilitiesControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtFacilityServiceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/list/AdminFacilityServiceTest.java
src/test/resources/facilities.json
src/test/resources/facility.json

https://tools.hmcts.net/jira/browse/FACT-838
Adding Court Facilities end points
```
[ ] Yes
[X] No
```

Adding Court Facilities end points

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtAreaOfLawEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/list/AdminAreasOfLawEndpointTest.java
src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/CourtAreaOfLawRepositoryTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtAreasOfLawController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/list/AdminAreasOfLawController.java
src/main/java/uk/gov/hmcts/dts/fact/entity/AreaOfLaw.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtAreaOfLaw.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/AreaOfLaw.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/AreasOfLawRepository.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtAreaOfLawRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtAreasOfLawService.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/list/AdminAreasOfLawService.java
src/main/resources/db/migration/V115__add_write_to_us_address_for_Ipswich_Court.sql
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtAreasOfLawControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/list/AdminAreasOfLawControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtAreasOfLawServiceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/list/AdminAreasOfLawServiceTest.java
src/test/resources/court-areas-of-law.json

https://tools.hmcts.net/jira/browse/FACT-826
```
[ ] Yes
[X] No
```

FACT-826 -  Implement CRUD endpoints for per court Areas of Law

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtAddressEndpointTest.java
src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/CourtRepositoryTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtAddressController.java
src/main/java/uk/gov/hmcts/dts/fact/mapit/MapitData.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtAddressService.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminService.java
src/main/java/uk/gov/hmcts/dts/fact/services/validation/PostcodeValidator.java
src/main/java/uk/gov/hmcts/dts/fact/services/validation/ValidationService.java
src/main/java/uk/gov/hmcts/dts/fact/util/AddressType.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtAddressControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtAddressServiceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminServiceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/validation/PostcodeValidatorTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/validation/ValidateServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-840
Validate input postcodes using Mapit for admin court addresses and update in-person court coordinates using primary address postcode
```
[ ] Yes
[x] No
```

FACT-840 - Admin update in-person court coordinates using Mapit for primary address postcode

---

src/main/resources/db/migration/V119__batch_court_changes_20.sql

FACT-856, FACT-721, FACT-722, FACT-717, FACT-860, FACT-772, FACT-716
```
[ ] Yes
[ x] No
```

FACT-856 adding migrations for content changes

---

src/main/resources/db/migration/V120__add_breathing_space_sidebar_for_county_courts.sql

https://tools.hmcts.net/jira/browse/FACT-806
Add breathing space to database for in-person county courts
```
[ ] Yes
[x] No
```

FACT-806 - Add breathing space to database for in-person county courts

---

src/main/resources/db/migration/V121__batch_court_amendment.sql

adding domestic violance to peterborough

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/dts/fact/config/FeignConfiguration.java

- Suppressed CVE's temporarily whilst we upgrade to SpringBoot 2.5.2
```
[ ] Yes
[x] No
```

Suppressed CVE temporarily

---

build.gradle
charts/fact-api/Chart.yaml
charts/fact-api/values.aat.template.yaml
charts/fact-api/values.yaml
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/dts/fact/mapit/MapitClientTest.java
src/main/resources/application.yaml
src/main/resources/bootstrap.yaml

- Reverted SpringBoot changes due to issues with DB connection blocking API pipeline
```
[ ] Yes
[x] No
```

Spring boot revert

---

src/main/resources/db/migration/V125__remove_single_justice_from_peterborough_court.sql

https://tools.hmcts.net/jira/browse/FACT-904
Remove single justice procedure from Peterborough Combines Court Centre
```
[ ] Yes
[x] No
```

FACT-904 - Remove single justice procedure from Peterborough Combines Court Centre

---

config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/list/AdminFacilitiesEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/list/AdminFacilitiesController.java
src/main/java/uk/gov/hmcts/dts/fact/entity/FacilityType.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/FacilityType.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/FacilityRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/list/AdminFacilityService.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/list/AdminFacilitiesControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/list/AdminFacilityServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-167
Added new endpoints to allow read, create, update and deletion of Facility Types.
```
[ ] Yes
[x] No
```

FACT-167 Added new endpoints to allow read, create, update and deletion of Facility Types.

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/list/AdminContactTypeEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/util/FunctionalTestBase.java
src/main/java/uk/gov/hmcts/dts/fact/config/security/SecurityConfiguration.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/list/AdminContactTypeController.java
src/main/java/uk/gov/hmcts/dts/fact/entity/ContactType.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/ContactRepository.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtContactRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/list/AdminContactTypeService.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/list/AdminContactTypeControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/list/AdminContactTypeServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-831
```
[ ] Yes
[x] No
```

adding Contact types list

---

build.gradle
config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/dts/fact/util/AdminFunctionalTestBase.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/util/FunctionalTestBase.java
src/functionalTest/resources/application.properties

https://tools.hmcts.net/jira/browse/FACT-462
fact api testing enhancements
```
[ ] Yes
[x] No
```

fact api testing enhancements

---

src/integrationTest/resources/birmingham-civil-and-family-justice-centre.json
src/integrationTest/resources/deprecated/aylesbury-magistrates-court-and-family-court.json
src/main/resources/db/migration/V135__amend_facilities_dropdown_options.sql
src/test/resources/full-birmingham-civil-and-family-justice-centre-entity.json

https://tools.hmcts.net/jira/browse/FACT-924
Create a new migration file, where it says Hearing Loop T and change to Hearing Loop. Remove Hearing Loop T from the facilities dropdown list.
```
[ ] Yes
[X] No
```

Created migration to amend facilities dropdown options

---

src/main/resources/db/migration/V136__amend_service_area_name.sql

https://tools.hmcts.net/jira/browse/FACT-1017
Added a migration to amend a service area name, in English and Welsh.
```
[ ] Yes
[X] No
```

Changed service area name from 'fgm' to 'fgm protection orders'

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/list/AdminOpeningTypeEndPointTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/list/AdminOpeningTypeController.java
src/main/java/uk/gov/hmcts/dts/fact/entity/OpeningType.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/OpeningTimeRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/list/AdminOpeningTypeService.java
src/main/java/uk/gov/hmcts/dts/fact/util/AuditType.java
src/main/resources/db/migration/V137__add_admintype_entries_for_opening_type.sql
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/list/AdminOpeningTypeControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/list/AdminOpeningTypeServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-910
checking in opening types list endpoints
```
[ ] Yes
[x] No
```

checking in opening types list endpoints

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtOpeningTimeEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtOpeningTimeController.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtOpeningTimeControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtOpeningTimeServiceTest.java

(https://tools.hmcts.net/jira/browse/FACT-914)
removing opening types old endpoint
```
[ ] Yes
[x ] No
```

removing opening types old endpoint

---

charts/fact-api/Chart.yaml
charts/fact-api/values.aat.template.yaml
charts/fact-api/values.preview.template.yaml
charts/fact-api/values.yaml

updating aat chart to get azure postgres db secrets

---

src/main/resources/db/migration/V138__batch_update_court_locations.sql

https://tools.hmcts.net/jira/browse/FACT-995
Batch update of court latitude and longitudes
```
[ ] Yes
[X] No
```

Batch update of court latitude and longitudes

---

README.md
src/main/java/uk/gov/hmcts/dts/fact/util/RepoUtils.java
src/main/java/uk/gov/hmcts/dts/fact/util/Utils.java
src/test/java/uk/gov/hmcts/dts/fact/util/RepoUtilsTest.java
src/test/java/uk/gov/hmcts/dts/fact/util/UtilsTest.java

checking sonarqube

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/SearchEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/SearchController.java
src/main/java/uk/gov/hmcts/dts/fact/model/CourtReferenceWithDistance.java
src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/SearchControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtReferenceWithDistanceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java

(https://tools.hmcts.net/jira/browse/FACT-1030)
adding spoe logic change for children area of law
```
[ ] Yes
[x ] No
```

adding spoe logic change for children area of law

---

src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtGeneralInfoService.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtGeneralInfoServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-872
Fixing bug with blank name
```
[ ] Yes
[x] No
```

FACT-872: Fixing bug

---

README.md
build.gradle
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtsEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/entity/Court.java
src/main/java/uk/gov/hmcts/dts/fact/entity/InPerson.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/NewCourt.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminService.java
src/main/java/uk/gov/hmcts/dts/fact/util/AuditType.java
src/main/resources/db/migration/V139__add_admintype_entries_for_creating_court.sql
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminServiceTest.java

added delete court endpoint, and new changes for story

---

build.gradle
src/main/resources/db/migration/V140__add_admintype_entries_for_deleting_court.sql

moving changes to new migration to fix conflict

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtsEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/NewCourt.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminService.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminServiceTest.java

updates to accept lon and lat

---

src/main/java/uk/gov/hmcts/dts/fact/services/admin/list/AdminAreasOfLawService.java

https://tools.hmcts.net/jira/browse/FACT-947
Fixing bug - Area of Law, Duplicate display name.
```
[ ] Yes
[X] No
```

Fact 947 - Duplicate display name bug

---

src/main/java/uk/gov/hmcts/dts/fact/model/admin/CourtGeneralInfo.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtGeneralInfoServiceTest.java

Revert "updating logic to reflect updates to business roles around box being …"

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtGeneralInfoEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/Court.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/CourtGeneralInfo.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtGeneralInfoService.java
src/main/resources/db/migration/V142__amend_search_inperson_table.sql
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtGeneralInfoControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtGeneralInfoServiceTest.java

FACT-1061
```
[ ] Yes
[x ] No
```

Fact 1061 changes

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtSpoeAreaOfLawEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtSpoeAreasOfLawController.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtAreaOfLawSpoe.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/SpoeAreaOfLaw.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtAreaOfLawSpoeRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtSpoeAreasOfLawService.java
src/main/java/uk/gov/hmcts/dts/fact/util/AuditType.java
src/main/resources/db/migration/V143__add_admintype_entries_for_updating_court._spoe_areas_of _law.sql
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtSpoeAreasOfLawControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtSpoeAreasOfLawServiceTest.java
src/test/resources/court-spoe-areas-of-law.json

https://tools.hmcts.net/jira/browse/FACT-982
adding spoe ares of law endpoints
```
[ ] Yes
[x ] No
```

adding spoe ares of law endpoints

---

build.gradle

updating further dependencies

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtGeneralInfoEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtsEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/html/sanitizer/OwaspHtmlSanitizer.java
src/main/resources/db/migration/V146__update_court_alert_datatype.sql

https://tools.hmcts.net/jira/browse/FACT-1121
```
[ ] Yes
[X ] No
```

Fact 1121 2

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtsEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminServiceAreaEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminServiceAreaController.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/NewCourt.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/ServiceAreaRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/ServiceAreaService.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminService.java
src/main/resources/db/migration/V147__update_default_for_catchment_type.sql
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminServiceAreaControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/ServiceAreaServiceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-1073
```
[ ] Yes
[x ] No
```

Fact 1057 service areas

---

charts/fact-api/Chart.yaml

updating java version to latest

---

build.gradle

addressing CVE-2022-21724 to fix failing nightly builds
```
[ ] Yes
[ ] No
```

address CVE-2022-21724

---

build.gradle

updating dependencies

---

config/owasp/suppressions.xml

address dependencies
```
[ ] Yes
[X ] No
```

address dependencies

---

config/owasp/suppressions.xml

address CVE-2016-1000027 on failing master build
```
[ ] Yes
[x] No
```

address CVE-2016-1000027

---

src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtGeneralInfoService.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtGeneralInfoServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-1040
Amending PUAS flag access level
```
[ ] Yes
[x] No
```

FACT-1040: Amending PUAS flag access level

---

src/main/resources/db/migration/V154__update_address_description_for_court_address.sql

https://tools.hmcts.net/jira/browse/FACT-1168
amend court description field to restrict to 100 characters
```
[ ] Yes
[x] No
```

amend court description field

---

.github/renovate.json

change renovate

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtAddressEndpointTest.java
src/integrationTest/resources/deprecated/aylesbury-magistrates-court-and-family-court.json
src/main/java/uk/gov/hmcts/dts/fact/entity/County.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtAddress.java
src/main/java/uk/gov/hmcts/dts/fact/model/CourtAddress.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/County.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/CourtAddress.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/CountyRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCountyService.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtAddressService.java
src/main/resources/db/migration/V155__add_county_table.sql
src/main/resources/db/migration/V156__county_migration_for_ existing_addresses.sql
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtAddressControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtAddressTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/admin/CourtAddressTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/deprecated/CourtWithDistanceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCountyServiceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtAddressServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-1171
adding county field to court addresses and county table 
```
[ ] Yes
[x ] No
```

adding county field to court addresses

---

build.gradle
charts/fact-api/Chart.yaml
config/owasp/suppressions.xml
src/main/resources/db/migration/V157__replace_address_spaces.sql

[FACT-1180](https://tools.hmcts.net/jira/browse/FACT-1180)
```
[ ] Yes
[ x] No
```

adding sql to remove double spaces

---

src/integrationTest/resources/deprecated/aylesbury-magistrates-court-and-family-court.json
src/main/resources/db/migration/V158__replace_address_spaces_cy.sql

removing extra spaces from welsh addresses

---

src/main/resources/db/migration/V160__fix_add_intro_para_to_service_centres.sql

migration to fix data issue

---

charts/fact-api/Chart.yaml
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtAdditionalLink.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtAddress.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtAreaOfLaw.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtFacility.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtLocalAuthorityAreaOfLaw.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminService.java
src/test/java/uk/gov/hmcts/dts/fact/entity/CourtFacilityTest.java
src/test/java/uk/gov/hmcts/dts/fact/entity/CourtLocalAuthorityAreaOfLawTest.java

https://tools.hmcts.net/jira/browse/FACT-923
Adding updatedAt timestamp for tabs where it was missing
```
[ ] Yes
[x] No
```

FACT-923: Adding updatedAt timestamp for tabs where it was missing

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminAuditEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/AuditRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminAuditService.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminAuditServiceTest.java

FACT-1065
```
[ ] Yes
[x] No
```

updating audit tests

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminAuditEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/AuditRepository.java

adding transactional and clearing existing audit entries

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminAuditEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/AuditRepository.java

Fact 1065 fix tests

---

src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtFacilityService.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtFacilityServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-1224
no functional change. just pushing the court facilities through owasp html sanitiser before saving 
```
[ ] Yes
[ x ] No
```

FACT-1224 added owasp sanitizer for facilities

---

src/main/java/uk/gov/hmcts/dts/fact/model/Court.java
src/main/java/uk/gov/hmcts/dts/fact/util/Utils.java
src/test/java/uk/gov/hmcts/dts/fact/util/UtilsTest.java

https://tools.hmcts.net/jira/browse/FACT-1225
replaced the striphtmlfromstring with owaspsanitizer.
front end changes: https://github.com/hmcts/fact-frontend/pull/610
```
[ ] Yes
[ x ] No
```

FACT-1225 replaced striphtml with owaspsanitizer

---

src/main/resources/db/migration/V167__address_types_2.sql

adding migration to point towards new address

---

src/main/resources/db/migration/V167__address_types_2.sql
src/main/resources/db/migration/V168__address_types_3.sql

Fact 1228 3

---

build.gradle
config/owasp/suppressions.xml
gradle/wrapper/gradle-wrapper.properties
src/main/java/uk/gov/hmcts/dts/fact/config/SwaggerConfiguration.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/FACT-1123
update springboot 2.7.3
```
[ ] Yes
[x] No
```

update springboot 2.7.3

---

Jenkinsfile_nightly
build.gradle
config/fortify-client.properties

adding fortify

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtAddressEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtPostcodeEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/exception/GlobalControllerExceptionHandler.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtAddressControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtPostcodeControllerTest.java

https://tools.hmcts.net/jira/browse/FACT-1178
changing exception toString to String.join
```
[ ] Yes
[ x ] No
```

FACT-1178 fixed api toString issue

---

src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtAreasOfLawController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtLocalAuthoritiesController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtPostcodeController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtTypesAndCodesController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/list/AdminLocalAuthoritiesController.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminRole.java

adding fact viewer to roles

---

src/main/resources/db/migration/V175__update_court_urgent_message.sql

https://tools.hmcts.net/jira/browse/FACT-1249
```
[ ] Yes
[x] No
```

remove court urgent message

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/dts/fact/controllers/SearchController.java
src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java

fixing incident

---

src/main/resources/db/migration/V176__update_contact_explanation_field.sql

https://tools.hmcts.net/jira/browse/FACT-1250
increased explanation field length
```
[ ] Yes
[x] No
```

increased explanation field length

---

src/main/java/uk/gov/hmcts/dts/fact/entity/Court.java
src/main/java/uk/gov/hmcts/dts/fact/model/Court.java
src/main/java/uk/gov/hmcts/dts/fact/model/deprecated/OldCourt.java
src/main/java/uk/gov/hmcts/dts/fact/util/CourtType.java
src/main/resources/db/migration/V176__add_courtcode_locationcode.sql
src/test/resources/court-types-and-codes.json

https://tools.hmcts.net/jira/browse/FACT-1257
added changes including to the database so it accepts family and tribunal court codes
```
[ ] Yes
[ x ] No
```

FACT-1257 adding api changes for family and tribunal court codes

---

build.gradle

updated postgres driver to fix CVE-2022-41946
```
[ ] Yes
[ x ] No
```

fixed CVE-2022-41946

---

src/main/resources/db/migration/V178__update_medway_postcode.sql

https://tools.hmcts.net/jira/browse/FACT-1269
update postcode for medway court primary address. used address to narrow result because id's could be different between environments
```
[ ] Yes
[ x ] No
```

FACT-1269 added migration for medway court postcode change

---

README.md
build.gradle
src/main/java/uk/gov/hmcts/dts/fact/entity/AdditionalLink.java
src/main/java/uk/gov/hmcts/dts/fact/entity/ApplicationUpdate.java
src/main/java/uk/gov/hmcts/dts/fact/entity/AreaOfLaw.java
src/main/java/uk/gov/hmcts/dts/fact/entity/Audit.java
src/main/java/uk/gov/hmcts/dts/fact/entity/ContactType.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtAdditionalLink.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtAddress.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtApplicationUpdate.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtAreaOfLaw.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtAreaOfLawSpoe.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtContact.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtDxCode.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtEmail.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtFacility.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtLocalAuthorityAreaOfLaw.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtOpeningTime.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtPostcode.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtSecondaryAddressType.java
src/main/java/uk/gov/hmcts/dts/fact/entity/Email.java
src/main/java/uk/gov/hmcts/dts/fact/entity/EmailType.java
src/main/java/uk/gov/hmcts/dts/fact/entity/Facility.java
src/main/java/uk/gov/hmcts/dts/fact/entity/FacilityType.java
src/main/java/uk/gov/hmcts/dts/fact/entity/OpeningTime.java
src/main/java/uk/gov/hmcts/dts/fact/entity/OpeningType.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/FACT-1161
remove start up warnings
```
[ ] Yes
[x] No
```

remove start up warnings

---

src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtTypesAndCodesService.java

https://tools.hmcts.net/jira/browse/FACT-1257
bugfix for court codes not clearing.
```
[ ] Yes
[ x ] No
```

FACT-1257 fixed issue of not clearing court codes for api

---

.github/dependabot.yml
build.gradle
config/owasp/suppressions.xml
renovate.json

https://tools.hmcts.net/jira/browse/FACT-1149
adding renovate.json
```
[ ] Yes
[x] No
```

add renovate.json

---

src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/ServiceAreaRepositoryTest.java
src/main/resources/db/migration/V181__add_money_claims_service_areas.sql

https://tools.hmcts.net/jira/browse/FACT-1194
Online Civil Money Claims Service Centre retro fix
```
[ ] Yes
[X] No
```

Online Civil Money Claims Service Centre retro fix

---

config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtAddressEndpointTest.java
src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/CourtAddressRepositoryTest.java
src/main/java/uk/gov/hmcts/dts/fact/entity/Court.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtAddress.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/CourtAddress.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtAddressService.java
src/main/resources/db/migration/V182__add_court_address_sort_order.sql
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtAddressControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/admin/CourtAddressTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtAddressServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-1202
adding address sort order
```
[ ] Yes
[x] No
```

adding address sort order

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/FACT-1202
address CVE-2022-45143
```
[ ] Yes
[x] No
```

address CVE-2022-45143

---

src/main/resources/db/migration/V183__correcting_court_address_sort_order.sql

https://tools.hmcts.net/jira/browse/FACT-1200
correct court address sort order issue
```
[ ] Yes
[x] No
```

correct court address sort order issue

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/CourtsEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtAddressEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtTypesAndCodeEndPointTest.java
src/main/java/uk/gov/hmcts/dts/fact/config/security/SecurityConfiguration.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/CourtsController.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtType.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/CourtType.java
src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtRepository.java
src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtAddressService.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtTypesAndCodesService.java
src/main/resources/db/migration/V184__add_courttype_search_name.sql
src/test/java/uk/gov/hmcts/dts/fact/controllers/CourtsControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtAddressControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtAddressTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtAddressServiceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtTypesAndCodesServiceTest.java
src/test/java/uk/gov/hmcts/dts/fact/util/MapCourtCodeTest.java
src/test/resources/full-court-model.json

https://tools.hmcts.net/jira/browse/FACT-1252
adding find courts by court types endpoint
```
[ ] Yes
[x] No
```

adding findByCourtTypes endpoint

---

Jenkinsfile_CNP
build.gradle
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminAuditService.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtPostcodeService.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtPostcodeServiceTest.java

fixing master branch
```
[ ] Yes
[x] No
```

fix failing test

---

charts/fact-api/values.yaml
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtFacilityEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtFacilityService.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtFacilityServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-1267
```
[ ] Yes
[x] No
```

remove court facility sort byy order for admin portal

---

src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminAuditEndpointTest.java

https://tools.hmcts.net/jira/browse/FACT-1267
disable audit functional test due master build failing
```
[ ] Yes
[x] No
```

disable audit tests

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/FACT-1276
resolve CVE-2022-45688
```
[ ] Yes
[x] No
```

resolve CVE-2022-45688

---

README.md
build.gradle
charts/fact-api/Chart.yaml
src/main/resources/db/migration/V189__update_service_area_court_data.sql

test build
```
[ ] Yes
[x] No
```

test build

---

build.gradle
charts/fact-api/Chart.yaml
config/owasp/suppressions.xml

changing version

---

build.gradle
src/main/resources/db/migration/V191__remove_orphan_application_updates.sql

update to remove orphans from db table

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/FACT-1393
```
[] Yes
[x] No
```

resolve CVE-2018-1258

---

build.gradle
config/owasp/suppressions.xml
src/main/resources/db/migration/V193__update_edinburgh_long_lat_again.sql

https://tools.hmcts.net/jira/browse/FACT-1405
redoing lat long it was incorrect before
```
[ ] Yes
[x] No
```

Redone Lat Long changes for Edinburgh Social Security and Child Support Tribunal

---

charts/fact-api/Chart.yaml
charts/fact-api/values.yaml

https://tools.hmcts.net/jira/browse/FACT-1429
```
[ ] Yes
[x] No
```

amend image name

---

build.gradle
config/owasp/suppressions.xml
src/main/resources/db/migration/V194__update_northampton_additonal_ info.sql

https://tools.hmcts.net/jira/browse/FACT-1437
```
[x] Yes
[ ] No
```

update northampton crown court info

---

build.gradle
config/owasp/suppressions.xml
src/main/resources/db/migration/V197__make_maintenance_enforcement_centre_not_in_person.sql

https://tools.hmcts.net/jira/browse/FACT-1523
```
[ ] Yes
[X] No
```

make Maintenance Enforcement Business Centre not in person

---

build.gradle
charts/fact-api/Chart.yaml
charts/fact-api/values.yaml
config/owasp/suppressions.xml
infrastructure/main.tf
infrastructure/state.tf
infrastructure/tf-db-flexible-secrets.tf
infrastructure/variables.tf

adding flex db for fact

---

src/main/resources/db/migration/V198__add_general_ form_link_ to_ all_ courts.sql

https://tools.hmcts.net/jira/browse/FACT-1529
```
[ ] Yes
[x] No
```

add general enquiry form to all active courts

---

charts/fact-api/Chart.yaml
charts/fact-api/values.yaml

https://tools.hmcts.net/jira/browse/FACT-1536
trying to stop lots of bad stuff happening
```
[ ] Yes
[ ] No
```

FACT-1536 fixing db connection

---

charts/fact-api/Chart.yaml
charts/fact-api/values.yaml
infrastructure/main.tf

Fix DB name in secrets and change values to flex

---

src/main/resources/db/migration/V199__close_south_west_regional_divorce_centre.sql

https://tools.hmcts.net/jira/browse/FACT-1534
```
[ ] Yes
[x] No
```

close south west regional divorce centre

---

infrastructure/main.tf
infrastructure/tf-db-flexible-secrets.tf

remove ss, change secret values

---

charts/fact-api/Chart.yaml
charts/fact-api/values.yaml

changing to non flex sn

---

src/main/resources/db/migration/V200__update_bury_st_edmunds_divorce_centre.sql

https://tools.hmcts.net/jira/browse/FACT-1538
```
[ ] Yes
[x] No
```

update bury st edmunds divorce centre

---

Jenkinsfile_nightly

after to afterSuccess

---

build.gradle

trying to fix sonarcloud reporting
```
[ ] Yes
[x] No
```

added back in xml and csv enabled

---

src/main/resources/application.yaml

Swagger update
```
[ ] Yes
[x] No
```

Yaml updates for swags

---

.github/workflows/swagger.yaml

https://tools.hmcts.net/jira/browse/FACT-1644
Updated swagger json file thats generated. 
```
[ ] Yes
[x] No
```

Update swagger github action

---

src/main/resources/db/migration/V201__remove_general_ form_link_ from_ all_ courts.sql

https://tools.hmcts.net/jira/browse/FACT-1647
remove general form link for all courts
```
[ ] Yes
[x] No
```

remove general form link for all courts

---

Jenkinsfile_nightly
build.gradle

disable fortify due to issues
```
[ ] Yes
[x] No
```

disabled fortify

---

src/main/resources/db/migration/V202__addtional_link_ in_ new_ tabs.sql

https://tools.hmcts.net/jira/browse/FACT-1636
migrate data so links open in new tab for
```
[ ] Yes
[x] No
```

migrate data so links open in new tab for

---

infrastructure/state.tf

Fix master
```
[ ] Yes
[x] No
```

Fix master

---

README.md

https://tools.hmcts.net/jira/browse/FACT-1675
added troubleshooting steps 
```
[ ] Yes
[x] No
```

FACT-1675 update readme for fact-api

---

src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminService.java

Fix code smell on master...hopefully

fix code smell

---

src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminService.java

Code smells

---

build.gradle

https://tools.hmcts.net/jira/browse/FACT-1829
remove properties-volume-spring-boot-starter
```
[ ] Yes
[x] No
```

remove properties-volume-spring-boot-starter

---

Jenkinsfile_CNP
Jenkinsfile_nightly
docker/database/Dockerfile

https://tools.hmcts.net/jira/browse/FACT-1881
Docker limit fix
```
[ ] Yes
[x] No
```

Docker limit fix

---

build.gradle
config/owasp/suppressions.xml
infrastructure/main.tf
infrastructure/state.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/FACT-1904
updating dependancies
```
[ ] Yes
[x] No
```

FACT-1904 dependancy updates

---

build.gradle

https://tools.hmcts.net/jira/browse/FACT-1947
fixing CVEs
```
[ ] Yes
[x] No
```

FACT-1947 CVEs

---

src/main/resources/db/migration/V205__add_court_of_protection_email_type.sql

https://tools.hmcts.net/jira/browse/FACT-1962
added option into database emailtype court of protection
```
[ ] Yes
[x] No
```

FACT-1962 added Court of Protection option

---

src/main/resources/db/migration/V207__add_new_region_scotland_and_update_courts.sql

https://tools.hmcts.net/jira/browse/FACT-1951
sql update for adding new region (Scotland) and attaching courts to newly added region  
```
[ ] Yes
[x] No
```

FACT-1951 add Scotland region and associated courts

---

build.gradle
config/owasp/suppressions.xml

Fixed vuln
```
[ ] Yes
[x] No
```

Fixed vuln

---

README.md
src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtAddressEndpointTest.java
src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtAddressController.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtAddress.java
src/main/java/uk/gov/hmcts/dts/fact/exception/GlobalControllerExceptionHandler.java
src/main/java/uk/gov/hmcts/dts/fact/exception/InvalidEpimIdException.java
src/main/java/uk/gov/hmcts/dts/fact/model/CourtAddress.java
src/main/java/uk/gov/hmcts/dts/fact/model/CourtForDownload.java
src/main/java/uk/gov/hmcts/dts/fact/model/admin/CourtAddress.java
src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtAddressService.java
src/main/java/uk/gov/hmcts/dts/fact/services/validation/ValidationService.java
src/main/resources/db/migration/V208__add_new_column_epim_id.sql
src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtAddressControllerTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/CourtForDownloadTest.java
src/test/java/uk/gov/hmcts/dts/fact/model/admin/CourtAddressTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtAddressServiceTest.java
src/test/java/uk/gov/hmcts/dts/fact/services/validation/ValidateServiceTest.java

https://tools.hmcts.net/jira/browse/FACT-1903
api changes for epim id
```
[ ] Yes
[x] No
```

FACT-1903 api changes for epim id

---

src/main/resources/db/migration/V208__add_new_column_epim_id.sql
src/main/resources/db/migration/V209__fix_null_issue.sql

https://tools.hmcts.net/jira/browse/FACT-2050
Fix bug with new 209 script, 208 was added before so needed adding back as was reverted.
```
[ ] Yes
[x] No
```

FACT-2050 fix bug

---

src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtAddressService.java

https://tools.hmcts.net/jira/browse/FACT-1903
fix master build
```
[ ] Yes
[x] No
```

FACT-1903 sonar fixes

---

src/test/java/uk/gov/hmcts/dts/fact/launchdarkly/LaunchDarklyClientTest.java

https://tools.hmcts.net/jira/browse/FACT-2036
update test to resolve sonar qube issue
```
[ ] Yes
[x] No
```

update test to resolve sonar qube issue

---

src/main/resources/db/migration/V211__update_photo_lat_long_as_prod.sql

https://tools.hmcts.net/jira/browse/FACT-2040
DO NOT MERGE
migration to set db of search_court by slug
columns:
- image_file
- lat
- lon
```
[ ] Yes
[x] No
```

FACT-2040 added migration for each env to update image_file, lat, long [DO NOT MERGE]

---

infrastructure/state.tf

https://tools.hmcts.net/jira/browse/FACT-2153
Upgrade to 4.16.0
```
[ ] Yes
[x] No
```

FACT-2153 Upgrade azurerm to 4.0.0+

---

build.gradle

https://tools.hmcts.net/jira/browse/FACT-2394
Move to Azure from JitPack.
```
[ ] Yes
[x] No
```

FACT-2394 Move to Azure

---

src/main/java/uk/gov/hmcts/dts/fact/entity/CourtAddress.java
src/main/java/uk/gov/hmcts/dts/fact/entity/CourtSecondaryAddressType.java

https://tools.hmcts.net/jira/browse/FACT-2446
```
[ ] Yes
[x] No
```

FACT-2446 added fix for TransientObjectException error
